### ISSUE TITLE
add guidelines/best practices for development

### ISSUE THREAD

**Issue by broomej** [Blue-Lab/assoc_pipeline#2]
Just so we're all on the same page. Here are a few things that came to mind:
* use `argparser` for command line args
* use RDS for input/output
* follow [Hadley's style guide](http://adv-r.had.co.nz/Style.html)

**Comment by smgogarten** [comment]
include `print(argv)` and `sessionInfo()` as a log of exactly what was run

**Comment by broomej** [comment]
Should this be in the README or somewhere else?

**Comment by smgogarten** [comment]
I think the README is intended for users rather than developers, but I'm not sure where the best place is. Maybe a separate markdown document?

**Comment by broomej** [comment]
Yeah, that makes sense to me
