### ISSUE TITLE
Add a script to determine genetic sex

### ISSUE THREAD

**Issue by broomej** [Blue-Lab/assoc_pipeline#47]
`PLINK  --check-sex` would be a good default option, but if there's a way to do it in R so we can save it to a .rds file

**Comment by ElizabethBlue** [comment]
GWASTools uses intensity data, maybe SeqVarTools uses something else like this since thinking about sequence data

**Comment by broomej** [comment]
I've been thinking a little more and I don't think that making a wrapper script that is just:
```
plink --bfile /path/to/files --check-sex
```
is really all that helpful. Instead, what I think would be useful would be an R function, so I'm moving this over to Blue-Lab/blPipeline#2
